export {default as Search} from './Search'
export {default as MyRecipes } from './MyRecipes'
export {default as NewRecipe } from './NewRecipe'
export {default as Settings } from './Settings'
export {default as Fridge } from './Fridge'
export {default as Recipe } from './Recipe'
export {default as Account } from './Account'
export {default as Infos } from './Infos'
export {default as Disconnect } from './Disconnect'
